web:
   image: nginx:latest
   restart: always
   container_name: docker-nginx
   ports:
   - "80:80"
   volumes:
   - ./code:/code
   - ./site.conf:/etc/nginx/conf.d/default.conf
   links:
   - php
   - mysql
php:
   build: ./php-fpm
   container_name: docker-php
   restart: always
   ports:
   - "9000:9000"
   volumes:
   - ./code:/code
   links:
   - mysql
mysql:
   image: mysql:5.7
   container_name: mysql
   restart: always
   ports:
   - "3306:3306"
   environment:
   - MYSQL_ROOT_PASSWORD=pass
phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   restart: always
   ports:
   - "8080:80"
   links:
   - mysql
   environment:
   - PMA_HOST=mysql
