web:
   image: nginx:latest
   container_name: docker-nginx
   ports:
   - "80:80"
   volumes:
   - ./code:/code
   - ./site.conf:/etc/nginx/conf.d/default.conf
   links:
   - php
   - mysql
php:
   image: php:7-fpm
   container_name: docker-php
   ports:
   - "9000:9000"
   volumes:
   - ./code:/code
   links:
   - mysql
mysql:
   image: mysql:latest
   container_name: mysql
   ports:
   - "3306:3306"
   environment:
   - MYSQL_ROOT_PASSWORD=pass
phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   ports:
   - "8080:80"
   links:
   - mysql
   environment:
   - PMA_HOST=mysql
